# Generated by Django 6.0.5 on 2026-06-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(max_length=2048)),
            ],
        ),
    ]
