# Generated by Django 6.0.3 on 2026-04-09 16:16

import web_deii_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPosts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('publish_date', models.DateField()),
                ('edited_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('area', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploader', models.CharField(max_length=255)),
                ('file', models.FileField(unique=True, upload_to=web_deii_app.models.file_path)),
                ('is_active', models.BooleanField(default=False)),
                ('publish_date', models.DateField()),
                ('subject_id', models.ManyToManyField(related_name='files_id', to='web_deii_app.subjects')),
            ],
        ),
    ]
