# Generated by Django 6.0.3 on 2026-04-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_deii_app', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
        migrations.RenameModel(
            old_name='NewsPosts',
            new_name='NewsPost',
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
