# Generated by Django 6.0.3 on 2026-04-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_deii_app', '0003_rename_files_file_rename_newsposts_newspost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='publish_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='edited_date',
            field=models.DateField(null=True),
        ),
    ]
