# Generated by Django 6.0.3 on 2026-04-25 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_deii_app', '0005_tag_file_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='approver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='subject_id',
            field=models.ManyToManyField(related_name='files', to='web_deii_app.subject'),
        ),
        migrations.AlterField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_files', to='web_deii_app.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
