# Generated by Django 6.0.5 on 2026-05-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_deii_app', '0006_alter_file_approver_id_alter_file_subject_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
