# Generated by Django 6.0.5 on 2026-05-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_deii_app', '0009_file_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
