# Generated by Django 6.0.5 on 2026-05-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_deii_app', '0010_delete_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='NewsPost',
        ),
    ]
