# Generated by Django 6.0.5 on 2026-06-03 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=255)),
                ('year', models.IntegerField(choices=[(1, 'primero'), (2, 'segundo'), (3, 'tercero'), (4, 'cuarto'), (5, 'quinto'), (6, 'sexto'), (7, 'master'), (8, 'phd')], default=1)),
                ('semester', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'anual')], default=1)),
                ('area', models.ManyToManyField(to='subjects_app.knowledgearea')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjects_app.degree')),
            ],
        ),
    ]
