# Generated by Django 6.0.5 on 2026-05-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('area', models.CharField(max_length=255)),
            ],
        ),
    ]
