# Generated by Django 6.0.5 on 2026-05-30 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='knowledge_area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(default='TEST', max_length=255),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='area',
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'anual')], default=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.IntegerField(choices=[(1, 'primero'), (2, 'segundo'), (3, 'tercero'), (4, 'cuarto'), (5, 'quinto'), (6, 'sexto'), (7, 'master'), (8, 'phd')], default=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjects_app.degree'),
        ),
        migrations.AddField(
            model_name='subject',
            name='area',
            field=models.ManyToManyField(to='subjects_app.knowledge_area'),
        ),
    ]
