# Generated by Django 6.0.5 on 2026-07-03 14:43

import news_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_newsimage_newspost_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to=news_app.models.news_image_path),
        ),
    ]
