# Generated by Django 6.0.5 on 2026-05-18 13:50

import django.db.models.deletion
import files_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_deii_app', '0010_delete_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('uploader', models.CharField(max_length=255)),
                ('file', models.FileField(unique=True, upload_to=files_app.models.pending_upload_path)),
                ('is_active', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_files', to=settings.AUTH_USER_MODEL)),
                ('subject_id', models.ManyToManyField(related_name='files', to='web_deii_app.subject')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_files', to='web_deii_app.tag')),
            ],
        ),
    ]
