# Generated by Django 6.0.5 on 2026-05-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0001_initial'),
        ('subjects_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='subject_id',
            field=models.ManyToManyField(related_name='files', to='subjects_app.subject'),
        ),
        migrations.AlterField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_files', to='files_app.tag'),
        ),
    ]
