# Generated by Django 6.0.5 on 2026-06-08 09:24

import files_app.models
import files_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='extension',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(unique=True, upload_to=files_app.models.pending_upload_path, validators=[files_app.validators.file_size_by_category_validator, files_app.validators.extension_whitelist_validator]),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploader',
            field=models.EmailField(max_length=255),
        ),
    ]
