# Generated by Django 6.0.5 on 2026-06-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0002_file_extension_alter_file_file_alter_file_uploader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='subject_id',
            new_name='subjects',
        ),
        migrations.AlterField(
            model_name='file',
            name='extension',
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
    ]
