# Generated by Django 6.0.5 on 2026-06-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0003_rename_subject_id_file_subjects_alter_file_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='is_active',
        ),
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Aprobado'), (2, 'Denegado')], default=0),
        ),
    ]
