# Generated by Django 6.0.5 on 2026-06-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0004_remove_file_is_active_file_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
